# Generated by Django 5.2.15 on 2026-07-23 10:14

import django.core.validators
from django.db import migrations, models


def fill_price_at_order(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    
    order_items = OrderItem.objects.select_related('product').all()
    
    for item in order_items:
        item.price_at_order = item.product.price
    
    OrderItem.objects.bulk_update(order_items, ['price_at_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_phone_number_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена на момент заказа'),
        ),
        migrations.RunPython(
            fill_price_at_order
        ),
    ]
