# Generated by Django 5.2.15 on 2026-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Необработан'), ('Preparing', 'Собирается'), ('Delivering', 'Курьер везет заказ'), ('Done', 'Выполнен')], default='Pending', max_length=20),
        ),
    ]
