# Generated by Django 5.2.15 on 2026-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Необработан'), ('Preparing', 'Собирается'), ('Delivering', 'Курьер везет заказ'), ('Done', 'Выполнен')], db_index=True, default='Pending', max_length=20),
        ),
    ]
