# Generated by Django 5.2.15 on 2026-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Необработан'), ('Preparing', 'Собирается'), ('Delivering', 'Курьер везет заказ'), ('Done', 'Выполнен')], db_index=True, default='Pending', max_length=20, verbose_name='статус заказа'),
        ),
    ]
