# Generated by Django 5.2.15 on 2026-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('In cash', 'Наличными'), ('Online', 'Электронно')], db_index=True, default='In cash', max_length=20),
        ),
    ]
