# Generated by Django 5.2.16 on 2026-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('In cash', 'Наличными'), ('Online', 'Электронно'), ('', 'Не выбрано')], db_index=True, default='', max_length=20),
        ),
    ]
