# Generated by Django 5.2.16 on 2026-08-02 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена на момент заказа'),
        ),
    ]
